name: Test React CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code du dépôt
        uses: actions/checkout@v3

      - name: Installer les dépendances
        run: npm install

      - name: Lancer le build
        run: npm run build
