name: Test my app

on: [push]

jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
      - name: getting the code
        uses: actions/checkout@v3

      - name: install node js
        uses: actions/setup-node@v3

      - name: install dependencies
        run: npm install

      - name: Lancer le build
        run: npm run build
