name: Test React Ci

on: [push]

jobs:
  buildingJob:
    runs-on: ubuntu-latest

    steps:
      - name: Recupérer le code
        uses: actions/checkout@v3

      - name: Install Dependecies
        uses: actions/setup-node@v3

      - name: Lancer le build
        uses: npm run build
