name: Test my app

on: [push]

jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
      - name: getting the code
        uses: actions/checkout@v3

      - name: install node js
        uses: action/setup-node@v3

      - name: install dependencies
        uses: npm install

      - name: deploy
        uses: npm deploy
