name: react workflow

on: [push]

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - name: copy code
        uses: actions/checkout@v4

      - name: install node
        uses: actions/node-setup@v4

      - name: install dependencies
        run: npm install

      - name: run tests
        run: npm test a

      - name: run build
        run: npm build
